### PR TITLE
PR for CI

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by kba** [comment]
@zuphilip This PR is not required anymore, is it?

**Comment by zuphilip** [comment]
I am not sure, but I forgot at least about this PR. The idea was somehow to use it for CircleCI result?

**Comment by kba** [comment]
I think it was for the travis badge but travis is enabled for tmdev/ocropy now

**Comment by zuphilip** [comment]
Okay, then we can close it, I guess.

**Pull request closed without merging**
